version: '3'
services:
  pyspark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - .:/home/jovyan/work
    mem_limit: 4g   # Limit memory to 8 GB
    cpus: 3         # Limit CPU usage to 2 cores
